create table public.applications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid(),
  company text not null check (btrim(company) <> ''),
  company_key text not null check (btrim(company_key) <> ''),
  role text not null check (btrim(role) <> ''),
  location text not null default '',
  channel text not null default '',
  applied_date date,
  status text not null default '准备投递' check (status in (
    '准备投递', '已投递', '笔试', '面试中', '已录用', '已拒绝', '已放弃'
  )),
  next_action text not null default '',
  next_date date,
  salary text not null default '',
  contact text not null default '',
  job_url text not null default '',
  tags text[] not null default '{}',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.interviews (
  id uuid primary key default gen_random_uuid(),
  application_id uuid not null references public.applications(id) on delete cascade,
  user_id uuid not null default auth.uid(),
  date date not null,
  stage text not null check (btrim(stage) <> ''),
  rating smallint check (rating >= 0 and rating <= 5),
  questions text not null default '',
  highlights text not null default '',
  gaps text not null default '',
  next_plan text not null default '',
  feedback text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.status_history (
  id bigint generated by default as identity primary key,
  application_id uuid not null references public.applications(id) on delete cascade,
  user_id uuid not null default auth.uid(),
  status text not null check (status in (
    '准备投递', '已投递', '笔试', '面试中', '已录用', '已拒绝', '已放弃'
  )),
  changed_at timestamptz not null default now()
);

create index applications_user_company_updated_idx
  on public.applications (user_id, company_key, updated_at desc);
create index interviews_user_application_date_idx
  on public.interviews (user_id, application_id, date desc);
create index status_history_user_application_changed_idx
  on public.status_history (user_id, application_id, changed_at desc);

create function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    new.user_id = auth.uid();
    new.created_at = now();
  else
    new.user_id = old.user_id;
    new.created_at = old.created_at;
  end if;
  new.updated_at = now();
  return new;
end;
$$;

create function public.enforce_child_application_owner()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.applications
    where id = new.application_id
      and user_id = new.user_id
  ) then
    raise exception 'application_id must belong to the same user'
      using errcode = '23503';
  end if;
  return new;
end;
$$;

create function public.record_application_status()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.status_history (application_id, user_id, status)
  values (new.id, new.user_id, new.status);
  return new;
end;
$$;

create function public.set_status_history_values()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.user_id = auth.uid();
  new.changed_at = now();
  return new;
end;
$$;

create function public.touch_application_from_interview()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    update public.applications
    set updated_at = now()
    where id = old.application_id;
    return old;
  end if;

  if tg_op = 'UPDATE' and old.application_id is distinct from new.application_id then
    update public.applications
    set updated_at = now()
    where id = old.application_id;
  end if;

  update public.applications
  set updated_at = now()
  where id = new.application_id;
  return new;
end;
$$;

create trigger applications_assign_server_values
before insert or update on public.applications
for each row
execute function public.set_updated_at();

create trigger applications_record_status_on_insert
after insert on public.applications
for each row
execute function public.record_application_status();

create trigger applications_record_status_on_change
after update of status on public.applications
for each row
when (old.status is distinct from new.status)
execute function public.record_application_status();

create trigger interviews_assign_server_values
before insert or update on public.interviews
for each row
execute function public.set_updated_at();

create trigger interviews_enforce_application_owner
before insert or update on public.interviews
for each row
execute function public.enforce_child_application_owner();

create trigger status_history_assign_server_values
before insert on public.status_history
for each row
execute function public.set_status_history_values();

create trigger status_history_enforce_application_owner
before insert or update on public.status_history
for each row
execute function public.enforce_child_application_owner();

create trigger interviews_touch_application
after insert or update or delete on public.interviews
for each row
execute function public.touch_application_from_interview();

alter table public.applications enable row level security;
alter table public.interviews enable row level security;
alter table public.status_history enable row level security;

create policy applications_select_own on public.applications
for select using (auth.uid() = user_id);
create policy applications_insert_own on public.applications
for insert with check (auth.uid() = user_id);
create policy applications_update_own on public.applications
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy applications_delete_own on public.applications
for delete using (auth.uid() = user_id);

create policy interviews_select_own on public.interviews
for select using (auth.uid() = user_id);
create policy interviews_insert_own on public.interviews
for insert with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.applications
    where applications.id = application_id
      and applications.user_id = auth.uid()
  )
);
create policy interviews_update_own on public.interviews
for update using (auth.uid() = user_id) with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.applications
    where applications.id = application_id
      and applications.user_id = auth.uid()
  )
);
create policy interviews_delete_own on public.interviews
for delete using (auth.uid() = user_id);

create policy status_history_select_own on public.status_history
for select using (auth.uid() = user_id);
create policy status_history_insert_own on public.status_history
for insert with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.applications
    where applications.id = application_id
      and applications.user_id = auth.uid()
  )
);
create policy status_history_update_own on public.status_history
for update using (auth.uid() = user_id) with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.applications
    where applications.id = application_id
      and applications.user_id = auth.uid()
  )
);
create policy status_history_delete_own on public.status_history
for delete using (auth.uid() = user_id);

revoke insert, update, delete on table public.status_history from anon, authenticated;
grant select on table public.status_history to authenticated;
